/**
 * PULL API
 * REST api for static sport data.  Every resource is protected by an **API key** which must be placed in X-Api-Key request header:  X-Api-Key: your_api_key  and every request has to be made with client certificate.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003Probabilities'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2003Probabilities'));
  } else {
    // Browser globals (root is window)
    if (!root.RtsmunityPublicApiSdk) {
      root.RtsmunityPublicApiSdk = {};
    }
    root.RtsmunityPublicApiSdk.InlineResponse2003Markets = factory(root.RtsmunityPublicApiSdk.ApiClient, root.RtsmunityPublicApiSdk.InlineResponse2003Probabilities);
  }
}(this, function(ApiClient, InlineResponse2003Probabilities) {
  'use strict';




  /**
   * The InlineResponse2003Markets model module.
   * @module model/InlineResponse2003Markets
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2003Markets</code>.
   * @alias module:model/InlineResponse2003Markets
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>InlineResponse2003Markets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003Markets} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003Markets} The populated <code>InlineResponse2003Markets</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('market_id')) {
        obj['market_id'] = ApiClient.convertToType(data['market_id'], 'Number');
      }
      if (data.hasOwnProperty('market_state_id')) {
        obj['market_state_id'] = ApiClient.convertToType(data['market_state_id'], 'Number');
      }
      if (data.hasOwnProperty('win_selections')) {
        obj['win_selections'] = ApiClient.convertToType(data['win_selections'], ['Number']);
      }
      if (data.hasOwnProperty('probabilities')) {
        obj['probabilities'] = ApiClient.convertToType(data['probabilities'], [InlineResponse2003Probabilities]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} market_id
   */
  exports.prototype['market_id'] = undefined;
  /**
   * @member {Number} market_state_id
   */
  exports.prototype['market_state_id'] = undefined;
  /**
   * @member {Array.<Number>} win_selections
   */
  exports.prototype['win_selections'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse2003Probabilities>} probabilities
   */
  exports.prototype['probabilities'] = undefined;



  return exports;
}));


