/**
 * PULL API
 * REST api for static sport data.  Every resource is protected by an **API key** which must be placed in X-Api-Key reques header:          X-Api-Key: your_api_key  and every request has to be made with client certificate.  
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2005', 'model/InlineResponse2006', 'model/InlineResponse2007'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2005'), require('../model/InlineResponse2006'), require('../model/InlineResponse2007'));
  } else {
    // Browser globals (root is window)
    if (!root.RtsmunityPublicApiSdk) {
      root.RtsmunityPublicApiSdk = {};
    }
    root.RtsmunityPublicApiSdk.LiveSeriesApi = factory(root.RtsmunityPublicApiSdk.ApiClient, root.RtsmunityPublicApiSdk.InlineResponse2005, root.RtsmunityPublicApiSdk.InlineResponse2006, root.RtsmunityPublicApiSdk.InlineResponse2007);
  }
}(this, function(ApiClient, InlineResponse2005, InlineResponse2006, InlineResponse2007) {
  'use strict';

  /**
   * LiveSeries service.
   * @module api/LiveSeriesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new LiveSeriesApi. 
   * @alias module:api/LiveSeriesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getSeries operation.
     * @callback module:api/LiveSeriesApi~getSeriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2005>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Live Series
     * 
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.leagueId ID of the league in the form of an integer
     * @param {Number} opts.tournamentId ID of the tournament in the form of an integer
     * @param {module:api/LiveSeriesApi~getSeriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/InlineResponse2005>}
     */
    this.getSeries = function(sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getSeries";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
        'league_id': opts['leagueId'],
        'tournament_id': opts['tournamentId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse2005];

      return this.apiClient.callApi(
        '/{sport}/live/series', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSeriesFeed operation.
     * @callback module:api/LiveSeriesApi~getSeriesFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2006} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Series feed
     * 
     * @param {Number} id ID of the match in the form of an integer
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering states
     * @param {module:api/LiveSeriesApi~getSeriesFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2006}
     */
    this.getSeriesFeed = function(id, sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getSeriesFeed";
      }

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getSeriesFeed";
      }


      var pathParams = {
        'id': id,
        'sport': sport
      };
      var queryParams = {
        'sequence': opts['sequence']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = InlineResponse2006;

      return this.apiClient.callApi(
        '/{sport}/live/series/{id}/feed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSeriesState operation.
     * @callback module:api/LiveSeriesApi~getSeriesStateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Series state
     * 
     * @param {Number} id ID of the series in the form of an integer
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering
     * @param {String} opts.expand Expand series detail
     * @param {module:api/LiveSeriesApi~getSeriesStateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.getSeriesState = function(id, sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getSeriesState";
      }

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getSeriesState";
      }


      var pathParams = {
        'id': id,
        'sport': sport
      };
      var queryParams = {
        'sequence': opts['sequence'],
        'expand': opts['expand']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/{sport}/live/series/{id}/state', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
