/**
 * PULL API
 * REST api for static sport data.  Every resource is protected by an **API key** which must be placed in X-Api-Key reques header:          X-Api-Key: your_api_key  and every request has to be made with client certificate.  
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003', 'model/InlineResponse2004', 'model/InlineResponse2002'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2003'), require('../model/InlineResponse2004'), require('../model/InlineResponse2002'));
  } else {
    // Browser globals (root is window)
    if (!root.RtsmunityPublicApiSdk) {
      root.RtsmunityPublicApiSdk = {};
    }
    root.RtsmunityPublicApiSdk.LiveMatchesApi = factory(root.RtsmunityPublicApiSdk.ApiClient, root.RtsmunityPublicApiSdk.InlineResponse2003, root.RtsmunityPublicApiSdk.InlineResponse2004, root.RtsmunityPublicApiSdk.InlineResponse2002);
  }
}(this, function(ApiClient, InlineResponse2003, InlineResponse2004, InlineResponse2002) {
  'use strict';

  /**
   * LiveMatches service.
   * @module api/LiveMatchesApi
   * @version 3.0.0
   */

  /**
   * Constructs a new LiveMatchesApi. 
   * @alias module:api/LiveMatchesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getMatchFeed operation.
     * @callback module:api/LiveMatchesApi~getMatchFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Match feed
     * 
     * @param {Number} id ID of the match in the form of an integer
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering states
     * @param {module:api/LiveMatchesApi~getMatchFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/InlineResponse2003}
     */
    this.getMatchFeed = function(id, sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getMatchFeed";
      }

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMatchFeed";
      }


      var pathParams = {
        'id': id,
        'sport': sport
      };
      var queryParams = {
        'sequence': opts['sequence']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/{sport}/live/matches/{id}/feed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchState operation.
     * @callback module:api/LiveMatchesApi~getMatchStateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Match state
     * 
     * @param {Number} id ID of the match in the form of an integer
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering
     * @param {String} opts.expand Expand match detail
     * @param {module:api/LiveMatchesApi~getMatchStateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/InlineResponse2004}
     */
    this.getMatchState = function(id, sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getMatchState";
      }

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMatchState";
      }


      var pathParams = {
        'id': id,
        'sport': sport
      };
      var queryParams = {
        'sequence': opts['sequence'],
        'expand': opts['expand']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/{sport}/live/matches/{id}/state', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchStatisticsFeed operation.
     * @callback module:api/LiveMatchesApi~getMatchStatisticsFeedCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Match statistics feed
     * 
     * @param {Number} id ID of the match in the form of an integer
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering states
     * @param {module:api/LiveMatchesApi~getMatchStatisticsFeedCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getMatchStatisticsFeed = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getMatchStatisticsFeed";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'sequence': opts['sequence']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{sport}/live/matches/{id}/statistics/feed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchStatisticsState operation.
     * @callback module:api/LiveMatchesApi~getMatchStatisticsStateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Match statistics state
     * 
     * @param {Number} id ID of the match in the form of an integer
     * @param {Object} opts Optional parameters
     * @param {Number} opts.sequence Sequence number for filtering
     * @param {String} opts.expand Expand match detail
     * @param {module:api/LiveMatchesApi~getMatchStatisticsStateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getMatchStatisticsState = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getMatchStatisticsState";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'sequence': opts['sequence'],
        'expand': opts['expand']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{sport}/live/matches/{id}/statistics/state', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatches operation.
     * @callback module:api/LiveMatchesApi~getMatchesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2002>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Live Matches
     * 
     * @param {String} sport Sport key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.leagueId ID of the league in the form of an integer
     * @param {Number} opts.tournamentId ID of the tournament in the form of an integer
     * @param {Number} opts.seriesId ID of the series in the form of an integer
     * @param {module:api/LiveMatchesApi~getMatchesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse2002>}
     */
    this.getMatches = function(sport, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMatches";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
        'league_id': opts['leagueId'],
        'tournament_id': opts['tournamentId'],
        'series_id': opts['seriesId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse2002];

      return this.apiClient.callApi(
        '/{sport}/live/matches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
