/**
 * PULL API
 * REST api for static sport data.  Every resource is protected by an **API key** which must be placed in X-Api-Key reques header:          X-Api-Key: your_api_key  and every request has to be made with client certificate.  
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2008', 'model/InlineResponse2009', 'model/InlineResponse20010', 'model/InlineResponse20011'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2008'), require('../model/InlineResponse2009'), require('../model/InlineResponse20010'), require('../model/InlineResponse20011'));
  } else {
    // Browser globals (root is window)
    if (!root.RtsmunityPublicApiSdk) {
      root.RtsmunityPublicApiSdk = {};
    }
    root.RtsmunityPublicApiSdk.MarketsApi = factory(root.RtsmunityPublicApiSdk.ApiClient, root.RtsmunityPublicApiSdk.InlineResponse2008, root.RtsmunityPublicApiSdk.InlineResponse2009, root.RtsmunityPublicApiSdk.InlineResponse20010, root.RtsmunityPublicApiSdk.InlineResponse20011);
  }
}(this, function(ApiClient, InlineResponse2008, InlineResponse2009, InlineResponse20010, InlineResponse20011) {
  'use strict';

  /**
   * Markets service.
   * @module api/MarketsApi
   * @version 3.0.0
   */

  /**
   * Constructs a new MarketsApi. 
   * @alias module:api/MarketsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getMarketCloseTimes operation.
     * @callback module:api/MarketsApi~getMarketCloseTimesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2008>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Markets close times
     * 
     * @param {String} sport Sport key
     * @param {module:api/MarketsApi~getMarketCloseTimesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse2008>}
     */
    this.getMarketCloseTimes = function(sport, callback) {
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMarketCloseTimes";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse2008];

      return this.apiClient.callApi(
        '/{sport}/market/close_times', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMarketResolveTimes operation.
     * @callback module:api/MarketsApi~getMarketResolveTimesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2008>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Markets resolve times
     * 
     * @param {String} sport Sport key
     * @param {module:api/MarketsApi~getMarketResolveTimesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse2008>}
     */
    this.getMarketResolveTimes = function(sport, callback) {
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMarketResolveTimes";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse2008];

      return this.apiClient.callApi(
        '/{sport}/market/resolve_times', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMarketSelections operation.
     * @callback module:api/MarketsApi~getMarketSelectionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2009>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Selections
     * 
     * @param {String} sport Sport key
     * @param {module:api/MarketsApi~getMarketSelectionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse2009>}
     */
    this.getMarketSelections = function(sport, callback) {
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMarketSelections";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse2009];

      return this.apiClient.callApi(
        '/{sport}/market/selections', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMarketStates operation.
     * @callback module:api/MarketsApi~getMarketStatesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse20010>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Markets states
     * 
     * @param {String} sport Sport key
     * @param {module:api/MarketsApi~getMarketStatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse20010>}
     */
    this.getMarketStates = function(sport, callback) {
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMarketStates";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse20010];

      return this.apiClient.callApi(
        '/{sport}/market/states', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMarkets operation.
     * @callback module:api/MarketsApi~getMarketsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse20011>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Markets
     * 
     * @param {String} sport Sport key
     * @param {module:api/MarketsApi~getMarketsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/InlineResponse20011>}
     */
    this.getMarkets = function(sport, callback) {
      var postBody = null;

      // verify the required parameter 'sport' is set
      if (sport == undefined || sport == null) {
        throw "Missing the required parameter 'sport' when calling getMarkets";
      }


      var pathParams = {
        'sport': sport
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = [InlineResponse20011];

      return this.apiClient.callApi(
        '/{sport}/markets', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
